### ISSUE TITLE
Use a different API with a more generous free tier

### ISSUE THREAD

**Issue by BoD** [caarmen/weather-slack-profile-photo#11]
This one looks promising: https://www.weatherapi.com/api-explorer.aspx

**Comment by caarmen** [comment]
Thanks for the suggestion! 🙏🏻 

Support for weatherapi.com is included in release 0.1.0.

Note that this release brings a breaking change to the `config.toml`.  Check the [release notes](https://github.com/caarmen/weather-slack-profile-photo/releases/tag/v0.1.0) for details.
